apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

namespace: tasktracking-app

images:
- name: docker.io/mxxnr1se/cloud-labs
  newName: docker.io/mxxnr1se/cloud-labs
  newTag: auth-latest

replicas:
- name: authservice-deployment
  count: 2

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
  options:
    allowNameChange: true
    allowKindChange: true
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/envFrom/0/configMapRef
      value: {name: authservice-configmap}
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: authservice
- path: patch-service.yaml
  target:
    kind: Service
  options:
    allowNameChange: true
    allowKindChange: true

configMapGenerator:
- name: authservice-configmap
  literals:
  - ASPNETCORE_ENVIRONMENT="Production"
  - ASPNETCORE_URLS="http://+:8080"
  - ExpiryMinutes="100"
  options:
    disableNameSuffixHash: true
