apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.clusterSecretStore.project }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterSecretStore.region }}
          clusterName: {{ .Values.clusterSecretStore.clusterName }}
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
