apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-external-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: "cloudflare_api_token"
    remoteRef:
      key: {{ .Values.externalSecret.deploymentPrefix }}-cloudflare-api-token
      version: latest
