apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: migration-external-secret
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: migration-secret
    creationPolicy: Owner
  data:
  - secretKey: "DB_ENDPOINT"
    remoteRef:
      key: {{ .Values.externalSecret.deploymentPrefix }}-db-endpoint
      version: latest
  - secretKey: "DB_USER"
    remoteRef:
      key: {{ .Values.externalSecret.deploymentPrefix }}-db-user
      version: latest
  - secretKey: "DB_PASSWORD"
    remoteRef:
      key: {{ .Values.externalSecret.deploymentPrefix }}-db-password
      version: latest
