apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: services-external-secret
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: service-secret
    creationPolicy: Owner
  data:
  - secretKey: "Key"
    remoteRef:
      key: {{ .Values.externalSecret.deploymentPrefix }}-services-key
      version: latest
  - secretKey: "ConnectionString"
    remoteRef:
      key: {{ .Values.externalSecret.deploymentPrefix }}-ConnectionString
      version: latest
