apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: cert-manager
spec:
  secretName: tls-wildcard
  dnsNames:
  - cloudlabs.website
  - '*.cloudlabs.website'
  issuerRef:
    name: {{ .Values.deploymentPrefix }}-letsencrypt-cluster-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,{{ .Values.appsNamespace }}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,{{ .Values.appsNamespace }}"
