apiVersion: batch/v1
kind: Job
metadata:
  namespace: tasktracking-app
  name: init-kafka
spec:
  template:
    spec:
      containers:
      - args:
        - kafka-topics.sh
        - --create
        - --if-not-exists
        - --topic
        - task_tracking_topic
        - --replication-factor=1
        - --partitions=1
        - --bootstrap-server
        - kafka:9092
        command:
        - /bin/bash
        image: bitnami/kafka:3.6
        name: init-kafka
        workingDir: /opt/bitnami/kafka/bin
      restartPolicy: Never
