apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: tasktracking-app
spec:
  ports:
  - port: 9092
    targetPort: 9092
  - port: 9094
    targetPort: 9094
  selector:
    app: kafka-app
  type: ClusterIP
