apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasktracking-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: tasktracking-apps

  source:
    repoURL: https://github.com/mxxnr1se/Cloud-Labs.git
    targetRevision: Lab4
    path: deployment/environments/demo/apps

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
