apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projectservice
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: tasktracking-apps

  source:
    repoURL: https://github.com/mxxnr1se/Cloud-Labs.git
    targetRevision: Lab4
    path: deployment/environments/demo/projectservice

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
