apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

namespace: tasktracking-app

images:
- name: docker.io/mxxnr1se/cloud-labs
  newName: docker.io/mxxnr1se/cloud-labs
  newTag: frontend-latest

replicas:
- name: frontend-deployment
  count: 2

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
  options:
    allowNameChange: true
    allowKindChange: true
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/securityContext/fsGroup
      value: 101
    - op: replace
      path: /spec/template/spec/securityContext/runAsGroup
      value: 101
    - op: replace
      path: /spec/template/spec/securityContext/runAsUser
      value: 101
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: nginx
    - op: remove
      path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
    - op: remove
      path: /spec/template/spec/containers/0/envFrom
    - op: remove
      path: /spec/template/spec/containers/0/readinessProbe
    - op: remove
      path: /spec/template/spec/containers/0/livenessProbe
- path: patch-service.yaml
  target:
    kind: Service
  options:
    allowNameChange: true
    allowKindChange: true
