apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-app
  name: kafka-data
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: standard-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
