spec:
  destination:
    server: https://kubernetes.default.svc

appsNamespace: tasktracking-app-namespace

deploymentPrefix: development

reflector:
  enabled: false
  version: 7.1.216

externalSecrets:
  enabled: false
  version: v0.9.5
  namespace: external-secrets
  gcpServiceAccount: external-secrets@proj.iam.gserviceaccount.com

externalSecretsConfigs:
  enabled: false
  repoURL: git@github.com:example/example.git
  version: master
  path: deployment/infrastructure/charts/external-secrets-configs
  clusterSecretStore:
    project: example
    region: europe-north1
    clusterName: primary
  externalSecret:
    namespace: default

kafka:
  enabled: false
  repoURL: git@github.com:example/example.git
  version: master
  path: deployment/infrastructure/charts/kafka

externalDNS:
  enabled: false
  version: v6.27.0
  domain: example.com

ingress:
  enabled: false
  version: v4.8.2
  namespace: ingress
  valuesRepoURL: git@github.com:example/example.git
  valuesVersion: master

certManager:
  enabled: false
  version: v1.13.1
  namespace: cert-manager

ingressCertConfigs:
  enabled: false
  repoURL: git@github.com:example/example.git
  version: master
  path: deployment/infrastructure/charts/ingress-cert-configs

jobs:
  enabled: false
  repoURL: git@github.com:example/example.git
  version: master
  path: deployment/infrastructure/charts/jobs
  migrationJob:
    namespace: default
    image: docker.io/mxxn1se/cloud-labs:migration
  initKafkaJob:
    namespace: default
