{{ if .Values.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.externalSecrets.version }}
    chart: external-secrets
    helm:
      values: |
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: {{ .Values.externalSecrets.gcpServiceAccount }}

  destination:
    namespace: {{ .Values.externalSecrets.namespace }}
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
{{ end }}
