{{ if .Values.ingress.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: {{ .Values.ingress.version }}
    chart: ingress-nginx
    helm:
      valueFiles:
      - $values/deployment/infrastructure/values/ingress-nginx-values.yaml
  - repoURL: {{ .Values.ingress.valuesRepoURL }}
    targetRevision: {{ .Values.ingress.valuesVersion }}
    ref: values

  destination:
    namespace: {{ .Values.ingress.namespace }}
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true
{{ end }}
