{{ if .Values.ingressCertConfigs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-cert-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  source:
    repoURL: {{ .Values.ingressCertConfigs.repoURL }}
    targetRevision: {{ .Values.ingressCertConfigs.version }}
    path: {{ .Values.ingressCertConfigs.path }}
    helm:
      values: |
        appsNamespace: {{ .Values.appsNamespace }}
        deploymentPrefix: {{ lower .Values.deploymentPrefix }}

  destination:
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
{{ end }}
