apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  namespace: {{ .Values.migrationJob.namespace }}
spec:
  template:
    spec:
      containers:
      - name: migration-container
        image: {{ .Values.migrationJob.image }}
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: migration-secret
      restartPolicy: Never
